# Generated by Django 6.0.5 on 2026-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Внутренний идентификатор сообщения')),
                ('external_message_id', models.CharField(help_text='Должен быть уникальным', max_length=255, unique=True, verbose_name='ID сообщения во внешней системе')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID пользователя во внешней системе')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('received', 'Принято'), ('processing', 'В обработке'), ('processed', 'Обработано'), ('failed', 'Ошибка')], db_index=True, default='received', max_length=20, verbose_name='Статус обработки')),
                ('message_type', models.CharField(choices=[('order_status', 'Текст содержит слово «заказ» или «order»'), ('operator_request', 'Текст содержит «оператор», «менеджер» или «operator»'), ('unknown', 'Остальные сообщения')], default='unknown', max_length=20, verbose_name='Тип сообщения после обработки')),
                ('response_text', models.TextField(verbose_name='Ответ пользователю')),
                ('error_text', models.TextField(blank=True, default='', help_text='Заполняется, если обработка завершилась неуспешно', verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания сообщения во внешней системе')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения webhook сервисом')),
                ('processed_at', models.DateTimeField(null=True, verbose_name='Дата завершения обработки')),
            ],
        ),
    ]
